//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbmsSrc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CbmsMainDbEntities : DbContext
    {
        public CbmsMainDbEntities()
            : base("name=CbmsMainDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessPartner> BusinessPartners { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<FundsPack> FundsPacks { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<InvoiceProduct> InvoiceProducts { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Pending> Pendings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<FullInvoice> FullInvoices { get; set; }
        public virtual DbSet<Investment> Investments { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
