//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbms_src
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        public string Deparment { get; set; }
        public string Manager { get; set; }
        public string Category { get; set; }
        public decimal Sum { get; set; }
        public string State { get; set; }
    }
}
