//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbmsSrc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pending
    {
        public int InvoiceID { get; set; }
        public System.DateTime PaymentDeadline { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
