-- CREATE USER --
CREATE USER app FOR LOGIN app
GO

-- GRANT PERMISSIONS --
GRANT SELECT, INSERT, UPDATE ON Invoices TO app
GO

GRANT SELECT ON BusinessPartners TO app
GO

GRANT SELECT ON Products TO app
GO

GRANT SELECT ON Departments TO app
GO

GRANT SELECT, INSERT ON History TO app
GO

GRANT SELECT, INSERT, DELETE ON Pending TO app
GO

GRANT SELECT ON Categories TO app
GO

GRANT SELECT, INSERT, UPDATE ON FundsPacks TO app
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON InvoiceProducts TO app
GO