INSERT INTO Products (CategoryID, Name)
VALUES (1, N'Zamrażarka Samsung'),
       (1, N'Lodówka Beko'),
       (2, N'Telewizor Phiplis'),
       (2, N'Telewizor Sony'),
       (3, N'Słuchawki Superlux'),
       (3, N'Słuchawki Snab'),
       (4, N'Samsung Galaxy S100'),
       (4, N'iPhone 200'),
       (5, N'Laptop Lenovo Legion 700'),
       (5, N'Laptop MSI X400'),
       (6, N'Xbox One'),
       (6, N'PlayStation 10'),
       (7, N'The Witcher 3: Wild Hunt'),
       (7, N'Dishonored 2'),
       (8, N'Nadanie przesyłki pocztowej'),
       (8, N'Instalacja sprzętu'),
       (8, N'Naprawa niegwarancyjna'),
       (8, N'Naprawa gwarancyjna'),
       (9, N'Klucz'),
       (9, N'Wkrętarka'),
       (9, N'Wiertło'),
       (10, N'Śruba'),
       (10, N'Kabel'),
       (10, N'Pamięć RAM 4GB SO-DIMM'),
       (10, N'Dysk HDD 1TB'),
       (11, N'Papier'),
       (11, N'Długopis'),
       (11, N'Teczka'),
       (11, N'Segregator'),
       (11, N'Koperta'),
       (11, N'Karton');


